apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/issue-temporary-certificate: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  name: observability-demo-ingress-ui
spec:
  ingressClassName: nginx
  rules:
    - host: #{DOMAIN}
      http:
        paths:
          - backend:
              service:
                name: demo-web-ui-service
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - #{DOMAIN}
      secretName: observability-demo-tls