apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-web-ui
  template:
    metadata:
      labels:
        app: demo-web-ui
    spec:
      initContainers:
        - name: config-injector
          image: busybox
          command: ['sh', '-c', 'cp /config/runtime-config.js /usr/share/nginx/html/runtime-config.js']
          volumeMounts:
            - name: runtime-config
              mountPath: /config
            - name: nginx-html
              mountPath: /usr/share/nginx/html
      containers:
        - name: demo-web-ui
          image: felixnotka/observability-demo-webui:#{RELEASE_NUMBER}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: runtime-config
          configMap:
            name: demo-web-ui-config
        - name: nginx-html
          emptyDir: {}
