apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    app: grafana
data:
  dashboards.yaml: |
    # Define dashboard provisioning here
  datasources.yaml: |
    # Define datasource provisioning here
