apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-config
  labels:
    app: otelcol
data:
  otel-collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            include_metadata: true
            endpoint: "0.0.0.0:4318"
            cors:
              allowed_origins:
                - http://*
                - https://*
    
    exporters:
      logging:
        verbosity: detailed
    
      loki:
        endpoint: "http://loki:3100/loki/api/v1/push"
        tls:
          insecure: true
    
      otlp:
        endpoint: "http://tempo:4317"
        tls:
          insecure: true
        sending_queue:
          queue_size: 100
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
    
    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
    
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, logging]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [loki, logging]
    
