apiVersion: v1
kind: Service
metadata:
  name: demo-api-service
  labels:
    app: demo-api
spec:
  type: ClusterIP
  selector:
    app: demo-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
