apiVersion: v1
kind: Service
metadata:
  name: demo-web-ui-service
  labels:
    app: demo-web-ui
spec:
  type: NodePort # Or LoadBalancer depending on your cluster setup
  selector:
    app: demo-web-ui
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 32080 # Optional: specify if you need a specific NodePort
