apiVersion: v1
kind: Service
metadata:
  name: loki-service
  labels:
    app: loki
spec:
  type: ClusterIP
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP
      name: http
